### ISSUE TITLE
Cannot spend from script and pay back to script in the same transaction.

### ISSUE THREAD

**Issue by Riley-Kilgore** [Berry-Pool/lucid#14]
When trying to spend a UTxO from a contract and spend a subset of that UTxO back to the contract the following error occurs:

`{"code":2,"info":"Wallet could not send the tx.","message":"\"transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (PPViewHashesDontMatch (SJust (SafeHash \\\"8418cd2dd198020bc9569dc564b3459bb820340b6ea04e2090360af4c5e61073\\\")) (SJust (SafeHash \\\"e0c20279f42f99018f0d5727e1336654f8f5209e0d9cb5699f9e0b7b1309afb9\\\")))])\""}`

Steps to reproduce:

1: Construct address for always successful validator.

`const exampleScript: SpendingValidator = { // This always evaluates true.
    type: 'Plutus',
    script:
        '4e4d01000033222220051200120011',
}

const exampleAddress: Address = C.EnterpriseAddress.new(
    0, // testnet
    C.StakeCredential.from_scripthash(
        C.PlutusScript.from_bytes(
            Buffer.from(exampleScript.script, 'hex'),
        ).hash(C.ScriptHashNamespace.PlutusV1),
    ),
)
    .to_address()
    .to_bech32();`

2: Fund the validator script.

`let tx: TxComplete
  tx = await Tx.new()
        .payToContract(exampleAddress, ANY_DATUM(), { lovelace: BigInt(5000000) })
        .complete();

  const signedTx = (await tx.sign()).complete();

  await signedTx.submit();
`
  
3: Spend from the validator, but send 2 ADA back to the contract.

`const utxo = (await Lucid.utxosAt(exampleAddress))[0];

  let tx: TxComplete
  tx = await Tx.new()
        .payToContract(exampleAddress, ANY_DATUM(), { lovelace: BigInt(2000000) }) // This breaks.
        .collectFrom([utxo], ANY_REDEEMER())
        .attachSpendingValidator(exampleScript)
        .complete();

  const signedTx = (await tx.sign()).complete();

  await signedTx.submit();
`

**Comment by Riley-Kilgore** [comment]
The same issue seems to occur when trying to spend multiple UTxOs from the same validator.

Based on the statement made in the stack exchange link below, it would appear that this is due to the cost model used.

> The PPViewHashesDontMatch error from Edit #2 is caused by protocol parameters file not having cost models field populated - this is a problem with blockfrost-cardano-cli not having access to cost models via Api resulting in script transactions failing. – 
[sorki](https://cardano.stackexchange.com/users/810/sorki)
 [Feb 2 at 13:10](https://cardano.stackexchange.com/questions/6934/ppviewhashesdontmatch-and-unspendableutxonodatumhash-error-on-redeeming-funds-fr#comment3186_6934)
 
I am not all that familiar with the cost model, I tried to use the values provided in my parameters file from the cli, (as they were different than the values present in Lucid), but this did not yield any positive results.

https://cardano.stackexchange.com/questions/6934/ppviewhashesdontmatch-and-unspendableutxonodatumhash-error-on-redeeming-funds-fr

**Comment by alessandrokonrad** [comment]
> 3: Spend from the validator, but send 2 ADA back to the contract.
> 
> `const utxo = (await Lucid.utxosAt(exampleAddress))[0];
> 
> let tx: TxComplete tx = await Tx.new() .payToContract(exampleAddress, ANY_DATUM(), { lovelace: BigInt(2000000) }) // This breaks. .collectFrom([utxo], ANY_REDEEMER()) .attachSpendingValidator(exampleScript) .complete();

Likely because ANY_DATUM is applied twice to the witness set. Once from the utxo you redeem from and once for the new output you create. I have to create a hashmap for datums and check if they were already added

**Comment by alessandrokonrad** [comment]
Ah no I'm doing that already. However I realize a strange behaviour applying multiple datums, when they are the same or a specific numbers. I'm looking into it. It's somewhere in the serialization-lib.

**Comment by alessandrokonrad** [comment]
The costmodel must be correct already, because I'm able to spend from a script utxo. I feel like something is messed up with datum and redeeers rather.

**Comment by alessandrokonrad** [comment]
@Riley-Kilgore should be fixed now with `0.1.9`. Lemme know if everything works for you.

**Comment by zachyking** [comment]
@alessandrokonrad Withdraw 1 utxo and pay back to validator works. Withdrawing two utxos and paying back also works. Withdrawing 3 or more utxos and paying back results in the same error as before.

**Comment by alessandrokonrad** [comment]
@zachyking I forgot one little detail after getting the ex units back. I hope `0.2.0` resolves the issue.

**Comment by zachyking** [comment]
> @zachyking I forgot one little detail after getting the ex units back. I hope `0.2.0` resolves the issue.

Yes, confirmed: https://testnet.cardanoscan.io/transaction/e521ca28544a53bbb45c923db10ee91940144961a735d825394f2e2c240a24c1
Amazing, thank you!!

**Comment by Riley-Kilgore** [comment]
Highly appreciate your time and it seems that this issue is now resolved.

You are the real MVP @alessandrokonrad

**Comment by jonathanfishbein1** [comment]
I'm seem to be experiencing this issue with the following code 

`            const transaction =
                await lucid
                    .newTx()
                    .payToContract(scriptAddress
                        , Lucid.Data.empty()
                        , {
                            lovelace: BigInt(Number(3000000)),
                            'fda1b6b487bee2e7f64ecf24d24b1224342484c0195ee1b7b943db50434c415353494342414259424c55453031': BigInt(Number(4))
                        })
                    .collectFrom([utxo], serializedRedeemer)
                    .attachSpendingValidator(radSaleScript)
                    .addSigner(await lucid.wallet.address())
                    .payToAddress('addr_test1vrh0kkuahtz28qpfdhsx2hm2eekf06des8h03xnm757u65sd6egwy'
                        , { lovelace: lovelaceAmount })
                    .payToAddress(await lucid.wallet.address(), {
                        lovelace: minLovelaceAmount
                        , 'fda1b6b487bee2e7f64ecf24d24b1224342484c0195ee1b7b943db50434c415353494342414259424c55453031': BigInt(Number(1))
                    })
                    .complete()`

I'm using lucid-cardano version 0.3.5
