### ISSUE TITLE
TransactionBuilder.add_input() throw  RuntimeError: unreachable

### ISSUE THREAD

**Issue by judeebene** [Berry-Pool/lucid#16]
I was testing the sample from [issue 14](https://github.com/Berry-Pool/lucid/issues/14) to reproduce.
Then i had another error that was not part of the issue.

I just want to confirm if anyone has encounter the same error or is related to  [issue 46](https://github.com/dcSpark/cardano-multiplatform-lib/issues/46)
<img width="697" alt="Screenshot 2022-04-27 at 5 48 19 pm" src="https://user-images.githubusercontent.com/4046859/165578970-52d81611-f531-49ef-9596-28d3c0b204e6.png">

**Comment by zachyking** [comment]
> 

are you using a native script ? (otherwise it shouldn't be related to [issue 46](https://github.com/dcSpark/cardano-multiplatform-lib/issues/46))

code to reproduce your error would be helpful

**Comment by alessandrokonrad** [comment]
> > 
> 
> are you staking with a native script ? (otherwise it shouldn't be related to [issue 46](https://github.com/dcSpark/cardano-multiplatform-lib/issues/46))
> 
> code to reproduce your error would be helpful
> 
> if you use a native script in general and there are some issues there might be some changes already done in dcSpark's repo, that need merging to the custom version of the multiplatform lib used in lucid

Staking with native script or any other native script combination should work already. I advanced the multiplatform myself to allow adding native scripts and plutus scripts to inputs, mints, certs and withdrawals, how the ledger allows it. I'm gonna test it myself. Maybe I forgot something

**Comment by judeebene** [comment]
@zachyking I was testing the sample from [issue 4](https://github.com/Berry-Pool/lucid/issues/14), you can try it as well but i think running the matchingNumbers example  too throw the same error.
I was testing it using version 0.2.0.
Thanks @alessandrokonrad , I will try it again today , Maybe it from me.

**Comment by zachyking** [comment]
> @zachyking I was testing the sample from [issue 4](https://github.com/Berry-Pool/lucid/issues/14), you can try it as well but i think running the matchingNumbers example throw the same error. I was testing it using version 0.2.0. Thanks @alessandrokonrad , I will try it again today , Maybe it from me.

[issue 4](https://github.com/Berry-Pool/lucid/issues/14) works here. Try to share the code if it still persists.

**Comment by zachyking** [comment]
RuntimeError: unreachable happens when you don't add datum to the utxos used in `collectFrom`

**Comment by judeebene** [comment]
@zachyking Confirm that's true  unreachable happens when you don't add datum to the utxos used in collectFrom
