### ISSUE TITLE
Usage with nodejs on a server

### ISSUE THREAD

**Issue by MartinSchere** [Berry-Pool/lucid#2]
This library supports node environments, however, the `complete` method calls wallet methods that are not available on a server.

I think a better alternative would be to only depend on wallet functionality in specific methods like `.sign()` and have the ability to get the serialized transaction. That way, if you're building an API, you can still use this library and have the user send their UTxOs and collateral,  and you would have the user sign the resulting CBOR.

**Comment by alessandrokonrad** [comment]
A wallet is implemented like this: https://github.com/Berry-Pool/lucid/blob/a8df82120df2b05a8c5ed28156bd8ecc46491a76/src/types.ts#L126-L135

We can create a new wallet type.
E.g. Lucid.selectWalletFromUtxos({address, utxos, collateral, rewardAddress?})

The functions signTx and submitTx are not implemented and simply throw an error when they are called.

You can also easily access the transaction after you call .complete(), which returns the class TxComplete, where you have access to the class variable txComplete, which is nothing else than a CSL Transaction, which you can then convert to bytes/hex

**Comment by MartinSchere** [comment]
Awesome. Will try it out

**Comment by MartinSchere** [comment]
I think this PR wraps the issue up
