### ISSUE TITLE
Question about leveraging `selectWalletFromPrivateKey`

### ISSUE THREAD

**Issue by Riley-Kilgore** [Berry-Pool/lucid#20]
I am trying to use Lucid within a project that does not leverage the browser -- as such I need to select a wallet from a private key instead of from a wallet provider. I continue to get the same error after repeated attempts to create a valid PrivateKey. I was wondering if someone, maybe @alessandrokonrad, would be able to provide some guidance around where I am going wrong?

1) Generate a new key-pair with `cardano-cli address key-gen`.
2) Run `echo <PRIVATE_KEY_STRING> | bech32 addr_sk > skeybech`
3) Use the value now present in the file `skeybech` to call `selectWalletFromPrivateKey(skeybech)`

Result: `(node:75356) UnhandledPromiseRejectionWarning: Invalid secret key`

Thank you :)

**Comment by alessandrokonrad** [comment]
https://github.com/Berry-Pool/lucid/blob/fd4e85137369d71b545cd736e467b6ecf046b6ab/src/lucid/lucid.ts#L81
Here you see how the serialization-lib tries to parse the private key from bech32. How does the private key look like you generate with the cli?

**Comment by Riley-Kilgore** [comment]
With a newly generated key-pair I followed the same process again, here is the private key generated from the cli:
`addr_sk1tqs2wmw7ehmcgrjwaj3020htzwzx9zlaq70hrepmr9mzzs8706zvrvc2syms0`

**Comment by alessandrokonrad** [comment]
> addr_sk1tqs2wmw7ehmcgrjwaj3020htzwzx9zlaq70hrepmr9mzzs8706zvrvc2syms0

This looks like a testnet address to me😅

**Comment by alessandrokonrad** [comment]
Looking at https://github.com/cardano-foundation/CIPs/tree/master/CIP-0005 it's actually correct. The serialization-lib does have a different bech_32 encoding of the private key somehow.

**Comment by Riley-Kilgore** [comment]
From @zachyking :

```
const newBech32PrivateKey = C.PrivateKey.generate_ed25519().to_bech32()

await Lucid.selectWalletFromPrivateKey(newBech32PrivateKey)
```

This appears to work just fine 🤷‍♂️

**Comment by Riley-Kilgore** [comment]
1. Generate a new key-pair with `cardano-cli address key-gen`.
2. Run `echo <PRIVATE_KEY_STRING> | bech32 ed25519_sk > skeybech`
3. Use the value now present in the file `skeybech` to call `selectWalletFromPrivateKey(keyInFile)`

This works, I supposed changing addr_sk to ed25519_sk is the only change that needed to be made.

Thanks again for your time, I am closing this issue now. 💯
