### ISSUE TITLE
Fourty two example fix

### ISSUE THREAD

**Issue by Et9797** [Berry-Pool/lucid#28]
Redeeming example currently not working because the utxo array's last index needs to be retrieved first followed by the first index
`await lucid.utxosAt(matchingNumberAddress))[0]` -> `await lucid.utxosAt(matchingNumberAddress)).slice(-1)[0]` or `pop()`

**Comment by alessandrokonrad** [comment]
Hey thanks! I know there are multiple utxos at the script address already. Your suggestion also only works if the last utxo is the one you created. Well the likelihood that someone else is creating another utxo at almost the same time is really low. So for the example we could take your suggestion.
