### ISSUE TITLE
How to use with mnemonics?

### ISSUE THREAD

**Issue by markrufino** [Berry-Pool/lucid#30]
First of all thanks for this library! CSL's syntax, documentation, and api's could've been more better. Anyway, I've tried creating bech32 private keys form 24-word mnemonics (generated from Nami / Eternl) but i'm not able to make them work here. Would love an example!

**Comment by markrufino** [comment]
Thanks @Riley-Kilgore , will check that out.

**Comment by alessandrokonrad** [comment]
Maybe I integrate mnemonic support natively into Lucid, but low priority right now. You could simply use the npm package `bip39` to convert the seed phrase into entropy, which can then be parsed by CSL: https://github.com/Emurgo/cardano-serialization-lib/blob/master/doc/getting-started/generating-keys.md

**Comment by markrufino** [comment]
Thanks guys. Solved it now. My mistake was that I was directly using the key generated from 

```
const key = CardanoWasm.Bip32PrivateKey.from_bip39_entropy(
  Buffer.from(entropy, 'hex'),
  Buffer.from(''),
);
```

After looking at both Lucid and CSL's code i've realized that I needed to do this first:

```
this.key.to_raw_key().to_bech32()
```

The result from the above then works with Lucid.

**Comment by markrufino** [comment]
Update: It doesn't seem to be the same wallet when I convert it to the raw key or i'm missing something here?

**Comment by alessandrokonrad** [comment]
Selecting a wallet from seedphrase was added in Lucid version 0.5.6.
