### ISSUE TITLE
Add full example for browser integration usage

### ISSUE THREAD

**Issue by ysfdev** [Berry-Pool/lucid#31]
Hello, 

I would like to add a contribution to help provide a simple end-to-end integration example to help new users quickly and easily get to test the library in their local environment without having to research additional setup requirements. 

I have created a [sample-ada-transfer](https://github.com/ysfdev/sample-ada-transfer/) to demonstrate a simple sample integration usage of the library on the client side. 

If you think it will be useful, I can create a PR to include the sample app in [src/examples](https://github.com/Berry-Pool/lucid/tree/main/src/examples)

_BTW, thank you for working on this great library!_ 

Thanks

**Comment by alessandrokonrad** [comment]
Hey, that is great. Sure we can add it to the repo. We could either add it to `src/examples` or simply add it to examples section in the the readme file. What do you think is better?

**Comment by ysfdev** [comment]
I think current basic example in the examples section is still good to highlight the core pieces. We can add the full sample-app in src/examples and put a reference in the examples section. For example, below the basic usage title. 

I will create a PR and we can discuss any additional adjustments in the PR.
