### ISSUE TITLE
How to get the `policyId` from `policyScript` file ?

### ISSUE THREAD

**Issue by ahaxu** [Berry-Pool/lucid#33]
Hi every one,

Via `cardano-cli` we can get the `policyId` from `policyScript` file
```
cardano-cli transaction policyid \
    --script-file sample.plutus.script
```
Is there any way to get `policyID` if we use `lucid` ?

Thank you!

**Comment by alessandrokonrad** [comment]
I assume `sample.plutus.script` contains the a cbor hex string right?
What you do is instantiate lucid and then:
```
const policyId = lucid.utils.validatorToScriptHash({type: "PlutusV1", script: "YOUR CBOR HEX"})
```

**Comment by ahaxu** [comment]
> I assume `sample.plutus.script` contains the cbor hex string right? What you do is instantiate lucid and then:
> 
> ```
> const policyId = lucid.utils.validatorToScriptHash({type: "PlutusV1", script: "YOUR CBOR HEX"})
> ```

thank you so much @alessandrokonrad, clear for me now.
