### ISSUE TITLE
Appears to be Incompatible with Plutarch generated CBOR

### ISSUE THREAD

**Issue by Riley-Kilgore** [Berry-Pool/lucid#42]
If I use https://github.com/Liqwid-Labs/agora/tree/staging/agora/Agora to obtain CBOR hex for scripts relating to Agora, I have found that all transactions that require validation with these scripts will throw
`"ScriptFailures": {
    "mint:0": [
      {
        "validatorFailed": {
          "error": "DeserialiseFailure 0 \"expected bytes\"",
          "traces": []
        }
      }
    ]
  }`
  
I believe this to be an issue related more generally to Plutarch (but haven't verified), it would appear based on conversations with other engineers, that the same process to procure CBOR for these scripts, the scripts are working fine with an alternative to Lucid that we would prefer to avoid due to overhead (https://github.com/Plutonomicon/cardano-transaction-lib), I am almost sure that this is a discrepancy in deserialization between the libraries used (custom CSL from mlabs vs custom CML in Lucid).

I'm not even really sure where to start looking, but will be spending my day trying to figure this out. Any help would be appreciated.

**Comment by alessandrokonrad** [comment]
Hey @Riley-Kilgore The on-chain format must be pretty much the same for any script. Maybe the script is simply raw without the cbor tag. Could you let me know the hex script you get from Agora?

**Comment by Riley-Kilgore** [comment]
`59053d0100003232323232323232323232323232323232323222323232533300e3370e9000001099191919299980919911919800925114a0664602e44a666034002244a0022666006603c002444600400626004603e0024a66602a66ebc00cc070c078004488c00800c48940040053012bd8799fd8799f58203a0e1f310055badf46d20f4e9b6966aba407f44bbb6502a93b641d74b0455813ff00ff00375860320082a666024a6601866e1ccc040dd7180c8029bab3019002480084cdc399911919199980998070010021199980a18078011bab30210012375a6044002290000a40006eb8c070c074c078008dd7180d980e8009bab301900233223374a9000198069ba90023300d375200297ae0375c603200a91100480084c8c8c8c8c8c8c94cc04cc94ccc06800440044cc07d24012a45786563757465207468726573686f6c64206973206c657373207468616e206f7220657175616c20746f000013371290000018a9980999299980d000880089980fa481294472616674207468726573686f6c64206973206c657373207468616e206f7220657175616c20746f20000013371290000010a9980999299980d000880089980fa48128566f7465207468726573686f6c64206973206c657373207468616e206f7220657175616c20746f20000013371290000008a9980999299980d000880089980fa4812b4472616674207468726573686f6c64206973206c657373207468616e20766f7465207468726573686f6c640000133712004002264a666034002200226603e9212d45786563757465207468726573686f6c64206973206c657373207468616e20766f7465207468726573686f6c6400001337100020066eb4c07cc08000cdd6980f0011bad301d002301d001301d301b301d00133223301149122446174756d206e6f7420666f756e6420696e20746865207472616e73616374696f6e003322333301922533301c0011225001153330193371e646eb8c084c08c004c080004010488c008c08800c4c008c084004004888c008c084c088c08c00c4894004cc88c8c8c94ccc068cdc3a400000426eb8c08400454cc07c01458c08c008c078004dd5000a4920476976656e2054784f757420646f6e657327742068617665206120646174756d00002001301a3017301c00137586034603660360046601c92119476f7665726e6f72206f7574707574206e6f7420666f756e64003300f23370e660226eb8c068018dd5980d180d980e000a40046eb0c06400c54cc05d24012245786163746c79206f6e6520746f6b656e2073686f756c64206265206d696e746564001615330174911f5265666572656e636564207574786f2073686f756c64206265207370656e7400163015301900130183018001301700130173015301700415330134914f5061747465726e206d61746368206661696c75726520696e2027646f2720626c6f636b2061742061676f72612f41676f72612f476f7665726e6f722f536372697074732e68733a3136393a352d34340016301700230120013754602460266028002446466e3c00c004dd71808000aba02233300800200100314a0446600240022a660160042c600a444a666012002244a0022a66600c6004601a0022446004601e006266006004601c0024466660066ea40080048ccc01888cdc01bad301100200148000dd58008a400044666600a44a666010002244a0022a66600a66ebcc02cc030004010488c008c03800c4c008c034004004888c008c04000c48940055cd1118019129998030008801899802180500098011805800919180111980100100091801119801001000aab9f2300530050015738aae755d0aba2230023754002aae79`

Above is the policy cbor that I'm having issues with.

**Comment by alessandrokonrad** [comment]
The script looks fine. So you are able to fully build the transaction without any errors? Only at submission it fails?

**Comment by alessandrokonrad** [comment]
> If instead of leveraging txBuilder.complete() I leverage txBuilder.build_tx() am able to get a transaction.

Ah I see you are doing this. You shouldn't hahaha. Execution units won't be calculated, that's why fees are too low.
My guess is that the `DeserialiseFailure 0` occurs because of wrongly used datums or redeemers.

**Comment by Riley-Kilgore** [comment]
No, if I just use standard methods to build the transaction I get the DeserialiseFailure mentioned initially.

Here's the code generating the Tx, I have had plenty of success with Lucid using PlutusTx generated CBOR in the past.

`const createGovernor = async () => {
    const lucid = await getLucid()
    let ad = await lucid.wallet.address();
    let utxos = await lucid.utxosAt(ad)
    utxos = utxos.filter((utxo) => {
        if (utxo.txHash == "3a0e1f310055badf46d20f4e9b6966aba407f44bbb6502a93b641d74b0455813" && utxo.outputIndex == 0) {
            return true;
        }
        console.log(utxo.txHash)
        console.log(utxo.outputIndex)
        return false;
    })

    const governorValidatorAddress = lucid.utils.validatorToAddress(governorValidator)
    const stateThread = lucid.utils.validatorToScriptHash(governorPolicy)

    const mintAssets : Assets = {}
    mintAssets[stateThread] = 1n;

    const spendToValidator : Assets = {}
    spendToValidator[stateThread] = 1n;
    spendToValidator['lovelace'] = 2000000n;

    const thresholds : [BigInt, BigInt, BigInt] = [0n, 0n, 0n];
    const initialProp = 0n;
    const timingConfig : [Date, Date, Date, Date] = [new Date(), new Date(), new Date(), new Date()];
    const maxWidth = new Date();
    const datum = GOVERNOR_DATUM(thresholds, initialProp, timingConfig, maxWidth)

    let tx = lucid.newTx()
        .collectFrom(utxos)
        .mintAssets(mintAssets, Data.empty())
        .attachMintingPolicy(governorPolicy)
        .payToContract(governorValidatorAddress, datum, spendToValidator)
    let txComplete = await tx.complete({changeAddress: ad, datum: datum})

    let txSigned = await txComplete.sign().complete()
    return await txSigned.submit();

}`

**Comment by Riley-Kilgore** [comment]
Here is some of the code used for reference:
`const createGovernor = async () => {
    const lucid = await getLucid()
    let ad = await lucid.wallet.address();
    let utxos = await lucid.utxosAt(ad)
    utxos = utxos.filter((utxo) => {
        if (utxo.txHash == "3a0e1f310055badf46d20f4e9b6966aba407f44bbb6502a93b641d74b0455813" && utxo.outputIndex == 0) {
            return true;
        }
        console.log(utxo.txHash)
        console.log(utxo.outputIndex)
        return false;
    })

    const governorValidatorAddress = lucid.utils.validatorToAddress(governorValidator)
    const stateThread = lucid.utils.validatorToScriptHash(governorPolicy)

    const mintAssets : Assets = {}
    mintAssets[stateThread] = 1n;

    const spendToValidator : Assets = {}
    spendToValidator[stateThread] = 1n;
    spendToValidator['lovelace'] = 2000000n;

    const thresholds : [BigInt, BigInt, BigInt] = [0n, 0n, 0n];
    const initialProp = 0n;
    const timingConfig : [Date, Date, Date, Date] = [new Date(), new Date(), new Date(), new Date()];
    const maxWidth = new Date();
    const datum = GOVERNOR_DATUM(thresholds, initialProp, timingConfig, maxWidth)

    let tx = lucid.newTx()
        .collectFrom(utxos)
        .mintAssets(mintAssets, Data.empty())
        .attachMintingPolicy(governorPolicy)
        .payToContract(governorValidatorAddress, datum, spendToValidator)
    let txComplete = await tx.complete({changeAddress: ad, datum: datum})

    let txSigned = await txComplete.sign().complete()
    return await txSigned.submit();

}`

The code for the Governor Datum:
`
const PROPOSAL_THRESHOLD = (
    countVoting : BigInt,
    //-- ^ How much GT minimum must a particular 'ResultTag' accumulate for it to pass.
    create : BigInt,
    //-- ^ How much GT required to "create" a proposal.
    //
    //-- It is recommended this be a high enough amount, in order to prevent DOS from bad
    //-- actors.
    startVoting : BigInt
    //-- ^ How much GT required to allow voting to happen.
    //-- (i.e. to move into 'VotingReady')
    ) => {
        const fieldsInner = C.PlutusList.new()
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(countVoting.toString())))
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(create.toString())))
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(startVoting.toString())))
        return C.PlutusData.new_constr_plutus_data(C.ConstrPlutusData.new(C.BigNum.from_str("0"), fieldsInner))
    }

const PROPOSAL_TIMING_CONFIG = (
    draftTime: Date,
    //-- ^ "D": the length of the draft period.
    votingTime: Date,
    //-- ^ "V": the length of the voting period.
    lockingTime: Date,
    //-- ^ "L": the length of the locking period.
    executingTime: Date
    //-- ^ "E": the length of the execution period.
    ) => {
        const fieldsInner = C.PlutusList.new()
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(draftTime.valueOf().toString())))
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(votingTime.valueOf().toString())))
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(lockingTime.valueOf().toString())))
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(executingTime.valueOf().toString())))
        return C.PlutusData.new_constr_plutus_data(C.ConstrPlutusData.new(C.BigNum.from_str("0"), fieldsInner))
    }

const GOVERNOR_DATUM = (
    thresholds: [BigInt, BigInt, BigInt],
    propId: BigInt,
    propTimings: [Date, Date, Date, Date],
    newProposalValidLength: Date
    ) => {
        const fieldsInner = C.PlutusList.new()
        const propThresholds = PROPOSAL_THRESHOLD(thresholds[0], thresholds[1], thresholds[2])
        const propTimingsPart = PROPOSAL_TIMING_CONFIG(propTimings[0], propTimings[1], propTimings[2], propTimings[3])

        fieldsInner.add(propThresholds)
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(propId.toString())))
        fieldsInner.add(propTimingsPart)
        fieldsInner.add(C.PlutusData.new_integer(C.BigInt.from_str(newProposalValidLength.valueOf().toString())))

        const datum = C.PlutusData.new_constr_plutus_data(C.ConstrPlutusData.new(C.BigNum.from_str("0"), fieldsInner))

        return toHex(datum.to_bytes());
}
`

**Comment by Riley-Kilgore** [comment]
There are multiple transactions with different Datums all failing with these scripts, is DeserialiseFailure to be expected if the shape of a datum is not as it ought to be according to the script?

Here's the shape of the datum in Haskell, but you'd need to track down the types inside of it in the repo mentioned above (Agora), talking to @emiflake it seems like the shape for the datum is correct.

**Comment by Riley-Kilgore** [comment]
Hmm...

After trying to submit this tx via the CLI more manually I am running into the same error, I am closing this issue for now

Thanks for the responses. :)

**Comment by alessandrokonrad** [comment]
> "ScriptFailures": { "mint:0": [ { "validatorFailed": { "error": "DeserialiseFailure 0 \"expected bytes\"", "traces": [] } } ] }

One more hint. As you see the validation fails for minting. This means that you do not even have to look at a datum. It can only be the redeemer who is likely wrong.

**Comment by Riley-Kilgore** [comment]
```
{
  "constructor": 0,
  "fields": [
    { "constructor": 0,
      "fields": [
	{ "int": 5000000 },
	{ "int": 1000 },
	{ "int": 100 }
	]
    },
    { "int": 0 },
    { "constructor": 0,
      "fields": [
	{ "int": 1000 },
	{ "int": 1000 },
	{ "int": 1000 },
	{ "int": 1000 }
	]
    },
    { "int": 1000 }
  ]
}
```

I have attempted to leverage the CLI for building this Tx. This is the json datum I used, I used a simple value of 42 for the redeemer.

```
cardano-cli transaction build --alonzo-era \
--testnet-magic 1097911063 \
--protocol-params-file pparams.json \
--tx-in 3a0e1f310055badf46d20f4e9b6966aba407f44bbb6502a93b641d74b0455813#0 --tx-in-collateral 4e49cd094d5471e675bc95e8f3fa3a3b477b5efad2f135e4d4e2e17fb3148b3c#0 \
--tx-out addr_test1wzg65gyg9zu5u6kl53rs3v4f73xy7ekx0ylnp9w2g60ak6qx6uq9e+"1 0c5d23b4ed67dfd318b498502016b067171e42231abd4a51cd804ed9" \
--tx-out-datum-embed-file govDatum.json \
--mint "1 0c5d23b4ed67dfd318b498502016b067171e42231abd4a51cd804ed9" \
--mint-script-file govMint.plutus \
--mint-redeemer-value 42 \
--change-address addr_test1vqh0ezxpwef6yq2k9nje0qk8zj9tgqj8tljqjxa2s7wh5qg04ge03 \
--out-file govTx.raw
```

This still fails with a DeserialiseFailure.. :(

**Comment by alessandrokonrad** [comment]
> > > "ScriptFailures": { "mint:0": [ { "validatorFailed": { "error": "DeserialiseFailure 0 "expected bytes"", "traces": [] } } ] }
> > 
> > 
> > One more hint. As you see the validation fails for minting. This means that you do not even have to look at a datum. It can only be the redeemer who is likely wrong.
> 
> The redeemer is not checked in the policy. The policy checks the datum placed on the State Thread instantiated.

Yeah, but it asks for bytes. You added 42 which is an integer. Try to add a simple redeemer like {"bytes": "30"}

**Comment by Riley-Kilgore** [comment]
@alessandrokonrad Just tried that and to no avail.

I also tried compiling a Plutarch script that *should* always succeed, but I am receiving the same error there as well.

If I compile PlutusTx, everything seems to work just fine -- This is my first time trying to build anything around a Plutarch generated script.

**Comment by Timekiller7** [comment]
@Riley-Kilgore, figured out your issue with Plutarch CBOR?

**Comment by lemmon-714** [comment]
@Riley-Kilgore @Timekiller7 without attempting to follow the thread, this seems vaguely fitting to the title: https://github.com/spacebudz/lucid/issues/94

Maybe it helps, please let me know.

**Comment by TotallyNotChase** [comment]
@Riley-Kilgore You're likely using the raw hex, not the CBOR hex - as mentioned already in this thread. CTL (the alternative you mention) uses raw hex. Nearly everything else uses CBOR hex (including Lucid) for scripts.

This isn't really related to either Plutarch or Lucid - but if you have questions about the encodings and their discrepancies, you can probably ask in the Plutonomicon discord or some similar UPLC support channel.
