### ISSUE TITLE
How does this even compile without Buffer as a dependency?

### ISSUE THREAD

**Issue by jonathanfishbein1** [Berry-Pool/lucid#44]
What am I missing?

**Comment by alessandrokonrad** [comment]
I'll remove Buffer and will have some native functions instead. Already working on this

**Comment by jonathanfishbein1** [comment]
Thank you for the quick respone.  Feel free to label this as a question. I was attempting to use the delegateTo function and was getting a runtime error in the getAddressDetails function of the utils.tx file.  When I investigated deeper I found the following runtime error thrown in the toHex function of utils.tx

`ReferenceError: Buffer is not defined
    at toHex (index.js:819:15)
    at Utils.getAddressDetails (index.js:721:15)
    at Tx.delegateTo (index.js:1274:43)
    at HTMLButtonElement.eval (index.ts:36:61)`

I was surprised to not see Buffer included in the dependencies

**Comment by alessandrokonrad** [comment]
> ReferenceError: Buffer is not defined at toHex (index.js:819:15) at Utils.getAddressDetails (index.js:721:15) at Tx.delegateTo (index.js:1274:43) at HTMLButtonElement.eval (index.ts:36:61)

In what environment did you run this? Node.js or Browser?

**Comment by alessandrokonrad** [comment]
Check the vasil branch: https://github.com/Berry-Pool/lucid/tree/vasil
I resolved everything already. That's where I'm currently working at.

**Comment by jonathanfishbein1** [comment]
Ok I think I see that webpack is loading in buffer via ProvidePlugin.  Why not an explict dependency on buffer and an explicit import in utils.ts?

**Comment by jonathanfishbein1** [comment]
I'm not able to sign this transaction?

` const transaction = await lucid
                                .newTx()
                             .delegateTo("stake1u9zxeq4uhzh39da2exq8rt30mv6tyt8r48gk299578wg3gg45qqs7", poolId).complete()

const signedTx = await transaction
                            .sign()
                            .complete()

                        const transactionHash = await signedTx
                            .submit()`

Any ideas?

**Comment by rajeevbbqq** [comment]
@jonathanfishbein1 How you are importing with webpack 5 from main branch?
