### ISSUE TITLE
How to import in browser properly?

### ISSUE THREAD

**Issue by elRaulito** [Berry-Pool/lucid#47]
Steps I have done so far:

1. Convert wasm to asm.js and then using browserify to allow it as standard js
2. importing the module in index.html succesfully!
3. Lucid is not in the cardano_multiplatform_lib_bg.js module :/

Where do I find the Lucid class?

**Comment by alessandrokonrad** [comment]
Hey why would you want to convert from wasm to asm.js in the first place? It makes the lib much slower

**Comment by elRaulito** [comment]
It was mainly because of this issue "Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/wasm"

And I saw that when using serialization browser version the webassembly file was a asm.js and it worked smooth in that case

This is what I am doing
`<script type="module" src="./cardano_multiplatform_lib.js"></script>`

Sorry for these basic stuff questions

**Comment by alessandrokonrad** [comment]
```html
<script type="module">
import { Lucid } from "https://unpkg.com/lucid-cardano@0.5.0/web/mod.js"
// ...
</script>
```

You can do this. That's from the vasil branch. I'm far more ahead there than on main and will merge everything into main as soon as the HFC occurs.

**Comment by elRaulito** [comment]
Thanks a lot!
