### ISSUE TITLE
"BabbageOutputTooSmallUtxo" error submitting testnet native asset transactions

### ISSUE THREAD

**Issue by hazryder** [Berry-Pool/lucid#50]
This was working pre-Vasil so I'm presuming it's related to the network fork; Attempting to build a simple tx containing an NFT and allowing Lucid to calculate the minimum required amount results in txs which error out in the wallet. Tested with Nami, Flint and Eternl with similar "OutputTooSmallUtxo" errors.

**Comment by alessandrokonrad** [comment]
Hey that is very likeley. You may wanna check the readme in vasil branch: https://github.com/Berry-Pool/lucid/tree/vasil. If you run Lucid `0.3.5`then yeah that is not compatible with the testnet anymore, only mainnet at the moment. the vasil branch should work fine on testnet

**Comment by hazryder** [comment]
Thanks @alessandrokonrad, I've switched to the vasil branch however I'm still getting errors when attempting to send txs. From Nami I get `Inputs do not conform to this spec or are otherwise invalid.` and from Flint I just get a vague `An error occurred during execution of this API call.`

**Comment by NickJorens** [comment]
This might be related to mine #51

**Comment by NickJorens** [comment]
Turns out you need use the Vasil version of Nami to use this library at the moment. :)

**Comment by Riley-Kilgore** [comment]
If you specify the amount of ADA to be large enough in the tx outputs by simply adding a new output everything works fine with 0.3.5, but I have not had any success with constructing transactions in 0.5.0 with anything other than very basic transactions, anything that requires minting of tokens does not work, (unless I am just crazy?). @alessandrokonrad

**Comment by alessandrokonrad** [comment]
> If you specify the amount of ADA to be large enough in the tx outputs by simply adding a new output everything works fine with 0.3.5, but I have not had any success with constructing transactions in 0.5.0 with anything other than very basic transactions, anything that requires minting of tokens does not work, (unless I am just crazy?). @alessandrokonrad

Mhh just works fine for me. Maybe let me know what you do exactly. You can open that in a separate issue.

**Comment by hazryder** [comment]
Closing this since my issue is resolved when using the Vasil branch of Lucid with the Vasil branch of Nami.
