### ISSUE TITLE
Unable to sign TX

### ISSUE THREAD

**Issue by NickJorens** [Berry-Pool/lucid#51]
Hi,

First of all, thank you very much for creating this library.
I've been trying to set this up in a Vue project but I'm getting an error when trying to sign the tx. 

```
import {Blockfrost, Lucid} from "lucid-cardano";

const lucid = await Lucid.new(
    new Blockfrost('https://cardano-testnet.blockfrost.io/api/v0', 'testnetnuzYcuNW9XxZ......4ynWX'),
    'Testnet'
);

// Assumes you are in a browser environment
const api = await window.cardano.nami.enable();
lucid.selectWallet(api);

const tx = await lucid.newTx()
.payToAddress('addr_test1qqm5k4qh02favw48dutgrwd5czqpddp4tn5nx7u2t5l0wu7027lyuwxkqk7ruc93hfknt6jsgdp8eh4fw3zly3fqwwcq3cwryn', {'lovelace': 500n} )
    .complete();
const signedTx = await tx.sign().complete();
const txHash = await signedTx.submit();
```

The error I get:
```Uncaught (in promise) {code: -1, info: 'Inputs do not conform to this spec or are otherwise invalid.'}```

The wallet has enough tADA in it. Nami is in testnet mode. 
When trying with Eternl it opens the sign window but there's no information about the tx and I also can't sign it.

I've tried to check if it can 'see' the wallet, when I enter invalid address it will tell me. If I exceed the amount of available tADA it will tell me. So it has access to the UTXO's

The solution is probably very simple, but after 4 hours, I'm unable to determine the cause.
Any help would be greatly appreciated!

**Comment by alessandrokonrad** [comment]
Hey, what Lucid version are you on?

**Comment by NickJorens** [comment]
I'm using the latest version from Vasil branch. 0.5.0

**Comment by alessandrokonrad** [comment]
Regarding Nami I can say it doesn't work with the vasil branch yet because it was not updated yet. If you want to try Nami with vasil there is a seperate version for it: https://github.com/Berry-Pool/nami-wallet/tree/vasil
You can find a download link in the readme.

**Comment by NickJorens** [comment]
Is there another way to test it? If Nami isnt supported and eternl isn't showing anything.

**Comment by alessandrokonrad** [comment]
Nami will support the Vasil changes as soon as the HF occurs on mainnet, but right now the testnet version of the official Nami extension still thinks it's in Alonzo. So in the meantime you can play with the seperate Vasil version of Nami.

**Comment by NickJorens** [comment]
I'm happy to report that this does fix the issue. I think I was misunderstanding your earlier message. My apologies!
