### ISSUE TITLE
Does Lucid have a way to sign Data?

### ISSUE THREAD

**Issue by NickJorens** [Berry-Pool/lucid#52]
Hi,

I'd love to use Lucid as a way to authenticate users. But from the API I couldn't find a way to sign data?
Is that already possible?

**Comment by alessandrokonrad** [comment]
I have plans to add that in the future, but low priority for now.

**Comment by alessandrokonrad** [comment]
Signing data/messages was added in the Lucid version 0.5.6.

**Comment by NickJorens** [comment]
> Signing data/messages was added in the Lucid version 0.5.6.

Thank you soo much!
This is great!
