### ISSUE TITLE
Problem submitting tx

### ISSUE THREAD

**Issue by jonathanfishbein1** [Berry-Pool/lucid#56]
I seem to be experiencing this issue 

`{
    "code": 2,
    "info": "Wallet could not send the tx.",
    "message": "\"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch (SJust (SafeHash \\\"f9e25ae86d80df1ac9713bd0ccc9d8e7fbe3b7c930fa2220bce514553f5993f5\\\")) (SJust (SafeHash \\\"4c8d7c07c919729a865b1f2e63a79603d4a68a43e28f079ad7e9e87bebc25075\\\"))))])\""
}`

with the following code

`const transaction = await lucid .newTx() .payToContract(scriptAddress , Lucid.Data.empty() , { lovelace: BigInt(Number(3000000)), 'fda1b6b487bee2e7f64ecf24d24b1224342484c0195ee1b7b943db50434c415353494342414259424c55453031': BigInt(Number(4)) }) .collectFrom([utxo], serializedRedeemer) .attachSpendingValidator(radSaleScript) .addSigner(await lucid.wallet.address()) .payToAddress('addr_test1vrh0kkuahtz28qpfdhsx2hm2eekf06des8h03xnm757u65sd6egwy' , { lovelace: lovelaceAmount }) .payToAddress(await lucid.wallet.address(), { lovelace: minLovelaceAmount , 'fda1b6b487bee2e7f64ecf24d24b1224342484c0195ee1b7b943db50434c415353494342414259424c55453031': BigInt(Number(1)) }) .complete()`

I'm using lucid-cardano version 0.3.5. I first experienced this using the cli as a start endpoint and lucid as a buy endpoint. I created a lucid start endpoint to rule out a protocol parameters mismatch but still encountered the error

I seem to have a similar problem to this

https://github.com/Berry-Pool/lucid/issues/14

Actually I'm also experiencing that error with the following transactions

`            const redeemer = new Lucid.Construct(1, [])
            const serializedRedeemer = Lucid.Data.to(redeemer)
            const datumHash = '923918e403bf43c34b4ef6b48eb2ee04babed17320d8d1b9ff9ad086e86f44ec'
            const utxo = (await lucid.utxosAt(scriptAddress)).filter(utxo => utxo.datumHash === datumHash && utxo.assets[currencySymbol + assetNameHex] !== undefined)
            console.log(utxo)
            const transaction =
                await lucid
                    .newTx()
                    .payToAddress('addr_test1qqfaj02yn24e38q8q4sea086yqem4tyt4n6seaxjaa4cnpzydjptew90z2m64jvqwxhzlke5kgkw82w3v52tfuwu3zssn2770q'
                        , {
                            lovelace: BigInt(Number(3000000))
                            , [currencySymbol + assetNameHex]: BigInt(Number(2))
                        })
                    .collectFrom(utxo, serializedRedeemer)
                    .attachSpendingValidator(radSaleScript)
                    .addSigner(await lucid.wallet.address())
                    .complete()
            const signedTx = await transaction
                .sign()
                .complete()
            const transactionHash = await signedTx
                .submit()`

Also getting this error with the matching numbers example?

**Comment by NickJorens** [comment]
Hey, try switching to the Vasil branch. I'm using 0.5.0 without any issues.

**Comment by jonathanfishbein1** [comment]
@NickJorens Thank you for your response, I've tried the 0.5.0 branch getting a different error!

`{code: -1, info: 'Inputs do not conform to this spec or are otherwise invalid.'}`

any ideas?

> Hey, try switching to the Vasil branch. I'm using 0.5.0 without any issues.

**Comment by lemmon-714** [comment]
This issue popped up recently for me as well, beforehand it worked. Anyone else experiencing this?

**Comment by lemmon-714** [comment]
Update - it's blockfrost.
