### ISSUE TITLE
Can't resolve 'wbg' in vasil version

### ISSUE THREAD

**Issue by judeebene** [Berry-Pool/lucid#57]
I noticed  this error when i removed the 0.3.5 version and install 0.5.0 vasil version

Module not found: Error: Can't resolve 'wbg' in 'node_modules/lucid-cardano/esm/src/core/wasm_modules/cardano-multiplatform-lib-web'

**Comment by alessandrokonrad** [comment]
Hey, does it happen during the installation of the package or when you try to run your script?

**Comment by judeebene** [comment]
Not during installation of the package

**Comment by judeebene** [comment]
This happen because of misconfigurations of my webback
