### ISSUE TITLE
lucid-cardano@0.5.1 might be incorrectly published

### ISSUE THREAD

**Issue by nejcr** [Berry-Pool/lucid#59]
I might be wrong we are using the code from vassil branch with npm( not Deno) and since `.ts` extensions are required for Deno npm needs to have ```dist``` folder published to the npm registry.   

Deno build task outputs correctly, but when looking at the contents of the published version https://registry.npmjs.org/lucid-cardano/-/lucid-cardano-0.5.1.tgz the `dist` folder is missing.
Version ```0.5.0``` is ok however

**Comment by alessandrokonrad** [comment]
Thank you! I indeed published the wrong folder. Going to fix this in a sec with a new version

**Comment by nejcr** [comment]
Thanks for the quick response
