### ISSUE TITLE
Package doesn't work for me with NextJS

### ISSUE THREAD

**Issue by zachyking** [Berry-Pool/lucid#6]
I tried to use this package with NextJS, unfortunately, unsuccessfuly.

- Create next app
- NPM install lucid-cardano
- Create component with a button using Lucid
- dynamically load on a page
- build -> error with topLevelAwait
- add webpack conf experiments: { asyncWebAssembly: true, topLevelAwait: true }
- build -> error with node-fetch dependencies

I managed to create a custom build that works with NextJS, however I didn't manage to create version suitable for all out of it. 
I did two things: 
1. I removed node-fetch import, NextJS has fetch out of the box,
2. I installed 'buffer' and added import { Buffer } from 'buffer' where it's used

I would really prefer to not use custom version of the lib, so if there is a way to fix it on my side, or if I can help for example with testing for this, please let me know.

**Comment by zachyking** [comment]
https://github.com/zachyking/cardano-lucid-nextjs example repo if it helps

**Comment by alessandrokonrad** [comment]
Is it possible that NextJs is somehow injecting a window object during server side rendering? Because the node-fetch import should only happen in a node.js environment since it's sits behind an if-statement that check if the window object exists.

**Comment by zachyking** [comment]
> Is it possible that NextJs is somehow injecting a window object during server side rendering? Because the node-fetch import should only happen in a node.js environment since it's sits behind an if-statement that check if the window object exists.

NextJS builds also server side, and there seem to be issue with node-fetch there, first of all it's not needed but it has some other dependencies, like 'fs' and uses some links like "node:buffer". I tried to do what I could in webpack config, fallbacks/plugins from what I found, but at the end I think 'fs' dependency was the main cause I couldn't fix, [as you should only use it only in getServerSideProps/getStaticProps it in nextjs](https://stackoverflow.com/questions/64926174/module-not-found-cant-resolve-fs-in-next-js-application).

**Comment by MartinSchere** [comment]
Maybe we can avoid the problem altogether if we used `axios`.

It's also cleaner

**Comment by GGAlanSmithee** [comment]
Perhaps you can use next.js [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import) with `ssr: false`.

**Comment by GGAlanSmithee** [comment]
Direct link: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by zachyking** [comment]
> Perhaps you can use next.js [dynamic import](https://nextjs.org/docs/advanced-features/dynamic-import) with `ssr: false`.

same result

**Comment by GGAlanSmithee** [comment]
@zachyking yeah my bad, I missunderstood the issue. After testing myself, I agree that the underlying issue is the usage of `node-fetch`. _Maybe_ there is a solution somewhere down the rabbit hole, but I agree it would make more sense to use an isomorphic library like axios instead.

**Comment by Benderjrk** [comment]
just a suggestion. It's got those observables I was talking about with axios https://www.npmjs.com/package/axios-observable

**Comment by alessandrokonrad** [comment]
Hey just released a new verison `0.1.4`. It should hopefully resolve the issues.

**Comment by zachyking** [comment]
> Hey just released a new verison `0.1.4`. It should hopefully resolve the issues.

Tested, issue with node-fetch doesn't seem to persist now, however Buffer is undefined
`TypeError: Cannot read properties of undefined (reading 'from')
    at Function.selectWallet (lucid.js`

**Comment by Benderjrk** [comment]
Maybe try something like this in your next.config
```
plugins: [
        new webpack.ProvidePlugin({
            Buffer: ['buffer', 'Buffer'],
        }),
        new webpack.ProvidePlugin({
            process: 'process/browser',
        }),
    ],

**Comment by zachyking** [comment]
> Maybe try something like this in your next.config
> 
> ```
> plugins: [
>         new webpack.ProvidePlugin({
>             Buffer: ['buffer', 'Buffer'],
>         }),
>         new webpack.ProvidePlugin({
>             process: 'process/browser',
>         }),
>     ],
> ```

unfortunately I tried that and it doesn't work, I have also:
`config.resolve.fallback = {
      buffer: require.resolve("buffer"),
    };`

**Comment by alessandrokonrad** [comment]
Okay it should work now with `0.1.5`. I tested it in Next.js, Gatsby, normal react with webpack and node.js. This whole ES module thing is a bit confusing, took me a bit now to figure out how it works.

**Comment by zachyking** [comment]
Confirmed, thank you!! 🚀
