### ISSUE TITLE
sample-ada-transfer example not working

### ISSUE THREAD

**Issue by lemmon-714** [Berry-Pool/lucid#67]
Following the instructions, this is what I get (vasil branch):

<img width="1280" alt="Screenshot 2022-08-27 at 17 47 19" src="https://user-images.githubusercontent.com/69039074/187037624-e1ee4ec7-e4cd-4844-9352-f13aa28c617d.png">

Maybe index.html is missing?

**Comment by alessandrokonrad** [comment]
Yes that is possible. This example was merged into the repository by someone else. I actually never ran it locally, was only looking at the .ts files, which do look fine to me. I have to look into it.

**Comment by lemmon-714** [comment]
Not sure if this is worth another issue, but the other example with Plutus V2 also stopped working a while ago, without changes on my side, and the error is coming from Blockfrost, saying
```
transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch (SJust (SafeHash \"e433278151c963c7d3a65cc63a610cc43b14dc79422a6fb4186c5ea71d8905c0\")) (SJust (SafeHash \"3444b089b81dd8b1e98c3bb8b40afdfc1b980e790685d597d26e24cd528a876e\"))))])
```
My guesses are that there was an update, and either lucid did not follow with blockfrost (unlikely, since that would have been noticed by now), or the update changed how the script (V2) is being compiled, thus outdating the example.

**Comment by alessandrokonrad** [comment]
> Not sure if this is worth another issue, but the other example with Plutus V2 also stopped working a while ago, without changes on my side, and the error is coming from Blockfrost, saying
> 
> ```
> transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch (SJust (SafeHash \"e433278151c963c7d3a65cc63a610cc43b14dc79422a6fb4186c5ea71d8905c0\")) (SJust (SafeHash \"3444b089b81dd8b1e98c3bb8b40afdfc1b980e790685d597d26e24cd528a876e\"))))])
> ```
> 
> My guesses are that there was an update, and either lucid did not follow with blockfrost (unlikely, since that would have been noticed by now), or the update changed how the script (V2) is being compiled, thus outdating the example.

I'm aware of this issue as I'm running into that myself for quite some time. Weirdly everything was working perfectly fine on one of the first testnets with the vasil changes. Since the public testnet bug was discovered things do not work anymore, also not on the other new testnets. It's a bit odd.

**Comment by alessandrokonrad** [comment]
> ```
> transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch (SJust (SafeHash \"e433278151c963c7d3a65cc63a610cc43b14dc79422a6fb4186c5ea71d8905c0\")) (SJust (SafeHash \"3444b089b81dd8b1e98c3bb8b40afdfc1b980e790685d597d26e24cd528a876e\"))))])
> ```

Found the issue now. Will push an update soon

**Comment by lemmon-714** [comment]
It works, thank you so much! Let me know if at any point in the future I can do something for you/the project.
