### ISSUE TITLE
Multiple Addresses

### ISSUE THREAD

**Issue by gerciljunio** [Berry-Pool/lucid#70]
I don't know if it went unnoticed by me, but does the package transact to multiple addresses? If not, do you have plans to have? Or, can we send a PR with this function? Thanks!

**Comment by alessandrokonrad** [comment]
I'm not sure if I get the question, but sending to multiple addresses works of course. For instance:
```
tx.payToAddress("addrx...",{lovelace:1000000n}).payToAddress("addry...", {lovelace:1000000n})
```
You can chain these functions together.

**Comment by gerciljunio** [comment]
Wow @alessandrokonrad, this is really cool! Thanks for your answer!
